app/entries/blueprint.py
import os

from flask import Blueprint, flash, redirect, render_template, request, url_for, g
from flask_login import login_required
from werkzeug import secure_filename

from helpers import object_list, entry_list, get_entry_or_404
from models import Entry, Category, Tag
from entries.forms import EntryForm, ImageForm
from app import app, db

entries = Blueprint('entries', __name__,
template_folder='templates')

#def entry_list(template, query, **context):
#    search = request.args.get('q')
#    if search:
#        query = query.filter(
#        (Entry.body.contains(search)) |
#        (Entry.title.contains(search)))
#    return object_list(template, query, **context)

@entries.route('/')
def index():
    entries = Entry.query.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/index.html', entries)

@entries.route('/categories/')
def category_index():
    categories = Category.query.order_by(Category.name)
    return object_list('entries/category_index.html', categories)

@entries.route('/categories/<slug>/')
def category_detail(slug):
    category = Category.query.filter(Category.slug == slug).first_or_404()
    entries = category.entries.order_by(Entry.created_timestamp.desc())
    return object_list('entries/category_detail.html', entries, category=category)

@entries.route('/tags/')
def tag_index():
    tags = Tag.query.order_by(Tag.name)
    return object_list('entries/tag_index.html', tags)

@entries.route('/tags/<slug>/')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    entries = tag.entries.order_by(Entry.created_timestamp.desc())
    return object_list('entries/tag_detail.html', entries, tag=tag)

@entries.route('/create/', methods=['GET'])
@login_required
def create():
    form = EntryForm()
    return render_template('entries/create.html', form=form)

@entries.route('/create/', methods=['POST'])
@login_required
def create_post():
    if request.method == 'POST':
        form = EntryForm(request.form)
        if form.validate():
            entry = form.save_entry(Entry(author=g.user))
            db.session.add(entry)
            db.session.commit()
            flash('Entry "%s" created successfully.' % entry.title, 'success')
            return redirect(url_for('entries.detail', slug=entry.slug))
        else:
            return 'error'

@entries.route('/image-upload/', methods=['GET', 'POST'])
@login_required
def image_upload():
    if request.method == 'POST':
        form = ImageForm(request.form)
        if form.validate():
            image_file = request.files['file']
            filename = os.path.join(app.config['IMAGES_DIR'], secure_filename(image_file.filename))
            image_file.save(filename)
            flash('Saved %s' % os.path.basename(filename), 'success')
            return redirect(url_for('entries.index'))
    form = ImageForm()
    return render_template('entries/image_upload.html', form=form)


@entries.route('/<slug>/')
def detail(slug): 
    entry = get_entry_or_404(slug, author=None)
    return render_template('entries/detail.html', entry=entry)

@entries.route('/<slug>/edit/', methods=['GET'])
@login_required
def edit(slug):
    entry = get_entry_or_404(slug, author=None)
    form = EntryForm(obj=entry)
    return render_template('entries/edit.html', entry=entry, form=form)

@entries.route('/<slug>/edit/', methods=['POST'])
@login_required
def edit_entry(slug):
    entry = get_entry_or_404(slug, author=None)
    if request.method == 'POST':
        form = EntryForm(request.form, obj=entry)
        if form.validate():
            entry = form.save_entry(entry)
            db.session.add(entry)
            db.session.commit()
            flash('Entry "%s" created successfully.' % entry.title, 'success')
            return redirect(url_for('entries.detail', slug=entry.slug))
        else:
            return 'error'

@entries.route('/<slug>/delete/', methods=['GET', 'POST'])
@login_required
def delete(slug):
    entry = get_entry_or_404(slug, author=None)
    if request.method == "POST":
        entry.status = Entry.STATUS_DELETED
        db.session.add(entry)
        db.session.commit()
        flash ('Entry %s" has been deleted.' % entry.title, 'success')
        return redirect(url_for('entries.index'))
    
    return render_template('entries/delete.html', entry=entry)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title> {% block title %}{% endblock %} | Wiki </title>
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
    <style type="text/css">
       /* body { padding-top: 50px; } */
    </style>
    {% block extra_styles %}{% endblock %}
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    {% block extra_scripts %}{% endblock %}
    </head>

    <body class="{% block body_class %}{% endblock %}">
        <div class="navbar navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">{% block branding %} Wiki Test Template {% endblock %}</a>
                </div>
                <div class = "collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url_for('homepage') }}">Home</a></li>
<!--                        <li><a href="{{ url_for('entries.category_index') }}">Categories</a></li> -->
                        <li><a href="{{ url_for('entries.index') }}">Entries</a></li>
                        <li><a href="{{ url_for('entries.tag_index') }}">Tags</a></li>
                        <li><a href="{{ url_for('entries.create') }}">Add</a></li>
                        {% if g.user.is_authenticated %}
                        <li><a href="{{ url_for('logout', next=request.path) }}">Logout</a></li>
                        {% else %}
                        <li><a href="{{ url_for('login', next=request.path) }}">Login</a></li>
                        {% endif %}
                        {% block extra_nav %}{% endblock %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <h1>{% block content_title %}{% endblock %}</h1>
                    {% for category, message in get_flashed_messages(with_categories=true) %}
                    <div class="alert alert-dismissable alert-{{ category }}">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        {{ message }}
                    </div>
                    {% endfor %}
                    {% block content %}
                    {% endblock %}
                </div>
                <div class="col-md-3">
                    {% block sidebar %}
                    <ul class="well nav nav-stacked">
                        <li><a href="#">Sidebar item</a></li>
                        <li><a href="#">Maybe Most Clicked?</a></li>
                    </ul>
                    {% endblock %}
                </div>
            </div>
            <div class="row">
                <hr />
                <footer>
                    <p>&copy; wiki_name</p>
                </footer>
            </div>
        </div>
    </body>
</html>

app/templates/homepage.html
{% extends "base.html" %}

{% block content_title %}This is the test template{% endblock %}

{# {% block content }
    {% if number %}
    <p>Your number is {{ number|int }}</p>
        <ul>
            {% for i in range(number|int) %}
                {% if i is divisibleby 2 %}
                    <li>{{ i }}</li>
                {% endif %}
            {% endfor %}
        </ul>
    {% else %}
        <p> No number specified.</p>
    {% endif %}

    <p>Your name is {{ name|default('<unknown>',True) }}. </p>
{% endblock %}
#}

app/templates/login.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}
{% block title %}Log in{% endblock %}
{%block content %}
<form action="{{ url_for('login', next=request.args.get('next', ''))}}" class="form-horizontal" method="post">
{{ form_field(form.email) }}
{{ form_field(form.password) }}
<div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
        <div class="checkbox">
            <label>{{ form.remember_me() }} Remember me</label>
        </div>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
        <button type="submit" class="btn btn-default">Log in</button>
        <a class="btn" href="{{ url_for('homepage') }}">Cancel</a>
    </div>
</div>
</form>
{% endblock %}